#!/usr/bin/env bash

binary=.build/release/CalSync
path=~/bin/calsync

if [ -n "$1" ] ; then
    path="$1"
fi

echo "Building.."
swift build -c release

echo "Copying ${binary} to ${path}.."
cp "${binary}" "${path}"

echo "Signing ${path}.."
codesign --force --sign - ${path}

